In [1]:
import pandas as pd

file_path = r"C:\Users\divya\Downloads\survey.csv"

df = pd.read_csv(r"C:\Users\divya\Downloads\survey.csv")

In [3]:
import warnings
warnings.simplefilter('ignore')

In [5]:
df.head()

,Timestamp,Age,Gender,Country,state,self_employed,family_history,treatment,work_interfere,no_employees,...,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence,comments
0,27-08-2014 11:29,37,Female,United States,IL,NaN,No,Yes,Often,Jun-25,...,Somewhat easy,No,No,Some of them,Yes,No,Maybe,Yes,No,NaN
1,27-08-2014 11:29,44,M,United States,IN,NaN,No,No,Rarely,More than 1000,...,Don't know,Maybe,No,No,No,No,No,Don't know,No,NaN
2,27-08-2014 11:29,32,Male,Canada,NaN,NaN,No,No,Rarely,Jun-25,...,Somewhat difficult,No,No,Yes,Yes,Yes,Yes,No,No,NaN
3,27-08-2014 11:29,31,Male,United Kingdom,NaN,NaN,Yes,Yes,Often,26-100,...,Somewhat difficult,Yes,Yes,Some of them,No,Maybe,Maybe,No,Yes,NaN
4,27-08-2014 11:30,31,Male,United States,TX,NaN,No,No,Never,100-500,...,Don't know,No,No,Some of them,Yes,Yes,Yes,Don't know,No,NaN

In [7]:
df.columns

Index(['Timestamp', 'Age', 'Gender', 'Country', 'state', 'self_employed',
       'family_history', 'treatment', 'work_interfere', 'no_employees',
       'remote_work', 'tech_company', 'benefits', 'care_options',
       'wellness_program', 'seek_help', 'anonymity', 'leave',
       'mental_health_consequence', 'phys_health_consequence', 'coworkers',
       'supervisor', 'mental_health_interview', 'phys_health_interview',
       'mental_vs_physical', 'obs_consequence', 'comments'],
      dtype='object')

In [9]:
df.describe(include='all')

,Timestamp,Age,Gender,Country,state,self_employed,family_history,treatment,work_interfere,no_employees,...,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence,comments
count,1259,1.259000e+03,1259,1259,744,1241,1259,1259,995,1259,...,1259,1259,1259,1259,1259,1259,1259,1259,1259,164
unique,884,NaN,49,48,45,2,2,2,4,6,...,5,3,3,3,3,3,3,3,2,160
top,27-08-2014 12:31,NaN,Male,United States,CA,No,No,Yes,Sometimes,Jun-25,...,Don't know,No,No,Some of them,Yes,No,Maybe,Don't know,No,* Small family business - YMMV.
freq,8,NaN,615,751,138,1095,767,637,465,290,...,563,490,925,774,516,1008,557,576,1075,5
mean,NaN,7.942815e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,2.818299e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,-1.726000e+03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,2.700000e+01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,3.100000e+01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,3.600000e+01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,1.000000e+11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
df['treatment'].value_counts()

treatment
Yes    637
No     622
Name: count, dtype: int64

In [13]:
df.isnull().sum()

Timestamp                       0
Age                             0
Gender                          0
Country                         0
state                         515
self_employed                  18
family_history                  0
treatment                       0
work_interfere                264
no_employees                    0
remote_work                     0
tech_company                    0
benefits                        0
care_options                    0
wellness_program                0
seek_help                       0
anonymity                       0
leave                           0
mental_health_consequence       0
phys_health_consequence         0
coworkers                       0
supervisor                      0
mental_health_interview         0
phys_health_interview           0
mental_vs_physical              0
obs_consequence                 0
comments                     1095
dtype: int64

In [15]:
df['work_interface'] = df['work_interfere'].fillna('Not specified')
df['self_employed'] = df['self_employed'].fillna('Not specified')

In [17]:
df = df.drop(columns=['state','comments'])

In [19]:
def get_response(row):
    if row['treatment']=='Yes':
        return "It's great that you've taken steps for your mental health. Remember you're not alone."
    elif row['treatment'] == 'No':
        return "It's okay if you haven't sought treatment yet. Seeking help is a sign of strength."
    else:
        return "I'm here to listen and support you."
df['chatbot_reply'] = df.apply(get_response, axis=1)

In [21]:
def get_response(row):
    if row['treatment'] == 'Yes':
        reply = "It's great that you've taken steps for your mental health. Remember you're not alone."
    elif row['treatment'] == 'No':
        reply = "It's okay if you haven't sought treatment yet. Seeking help is a sign of strength."
    else:
        reply = "I'm here to listen and support you."
    
    if row['work_interfere'] == 'Often':
        reply += " I understand itâ€™s impacting your work often. Let's think about some coping strategies."
    elif row['work_interfere'] == 'Sometimes':
        reply += " It's good to recognize this early and take small steps to care for yourself."
    
    return reply

df['chatbot_reply'] = df.apply(get_response, axis=1)

In [25]:
# Simple chatbot using your logic
treatment = input("Have you sought treatment for mental health? (Yes/No): ")
work_interfere = input("How often does mental health interfere with your work? (Often/Sometimes/Rarely/Never): ")

if treatment == 'Yes':
    reply = "It's great that you've taken steps for your mental health. Remember you're not alone."
elif treatment == 'No':
    reply = "It's okay if you haven't sought treatment yet. Seeking help is a sign of strength."
else:
    reply = "I'm here to listen and support you."

if work_interfere == 'Often':
    reply += " I understand itâ€™s impacting your work often. Let's think about some coping strategies."
elif work_interfere == 'Sometimes':
    reply += " It's good to recognize this early and take small steps to care for yourself."

print("\nChatbot:", reply)

Have you sought treatment for mental health? (Yes/No):  No
How often does mental health interfere with your work? (Often/Sometimes/Rarely/Never):  Rarely

Chatbot: It's okay if you haven't sought treatment yet. Seeking help is a sign of strength.

# Step-1: Add Sentiment & Emotion Detection

In [27]:
from transformers import pipeline

emotion_analyzer = pipeline('text-classification',
                            model='j-hartmann/emotion-english-distilroberta-base',
                            return_all_scores=False)
def detect_emotion(user_input):
    result = emotion_analyzer(user_input)[0]
    emotion = result['label']
    score = result['score']
    return emotion,score

text = 'I feel lonely and hopeless'
emotion, confidence = detect_emotion(text)
print(f'Detected emotion: {emotion} ({confidence:.2f})')

WARNING:tensorflow:From C:\Users\divya\anaconda3\Lib\site-packages\tf_keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

Device set to use cpu

Detected emotion: sadness (0.99)